### ISSUE TITLE
Issue running remnux/crits on Docker CE for Mac and Ubuntu

### ISSUE THREAD

**Issue by battletux** [REMnux/docker#18]
I have tried running this container on Docker for Mac but it keeps spitting out an error:

`$ sudo docker run --rm -it -v ~/crits-data:/home/nonroot/workdir -p 8443:8443 remnux/crits
Unable to find image 'remnux/crits:latest' locally
latest: Pulling from remnux/crits
8aec416115fd: Pull complete
695f074e24e3: Pull complete
946d6c48c2a7: Pull complete
bc7277e579f0: Pull complete
2508cbcde94b: Pull complete
8c5f76692058: Pull complete
c9c95511d79b: Pull complete
9296ab42c531: Pull complete
8ab6493f5e9b: Pull complete
bf7fa77e3078: Pull complete
02d7f025eb5a: Pull complete
1b64f006a9e1: Pull complete
a741d2087cbb: Pull complete
Digest: sha256:f9daf8f6884f43066c2cb8662008903ced075c72d8da51f29fa0c3378086a85b
Status: Downloaded newer image for remnux/crits:latest
2017-03-29 12:08:55,093 CRIT Set uid to user 999
2017-03-29 12:08:55,113 INFO RPC interface 'supervisor' initialized
2017-03-29 12:08:55,113 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-03-29 12:08:55,113 INFO supervisord started with pid 7
2017-03-29 12:08:56,121 INFO spawned: 'mongod' with pid 11
2017-03-29 12:08:56,123 INFO spawned: 'apache2' with pid 12
2017-03-29 12:08:57,173 INFO success: mongod entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-03-29 12:08:57,173 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
about to fork child process, waiting until server is ready for connections.
forked process: 82
child process started successfully, parent exiting
Traceback (most recent call last):
  File "/data/crits/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/crits/crits/settings.py", line 117, in <module>
    execfile(dbfile)
ValueError: invalid \x escape

$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true`

I was getting this on an older version of the Docker for Mac Beta so i removed that and installed the current stable version, however my issue still persists.

As such I ran this against a fresh install on a Ubuntu Server box and I get the same outcome:

`$ sudo docker run --rm -it -v ~/crits-data:/home/nonroot/workdir -p 8443:8443 remnux/crits
Unable to find image 'remnux/crits:latest' locally
latest: Pulling from remnux/crits
8aec416115fd: Pull complete
695f074e24e3: Pull complete
946d6c48c2a7: Pull complete
bc7277e579f0: Pull complete
2508cbcde94b: Pull complete
8c5f76692058: Pull complete
c9c95511d79b: Pull complete
9296ab42c531: Pull complete
8ab6493f5e9b: Pull complete
bf7fa77e3078: Pull complete
02d7f025eb5a: Pull complete
1b64f006a9e1: Pull complete
a741d2087cbb: Pull complete
Digest: sha256:f9daf8f6884f43066c2cb8662008903ced075c72d8da51f29fa0c3378086a85b
Status: Downloaded newer image for remnux/crits:latest
2017-03-29 12:20:15,255 CRIT Set uid to user 999
2017-03-29 12:20:15,276 INFO RPC interface 'supervisor' initialized
2017-03-29 12:20:15,276 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-03-29 12:20:15,276 INFO supervisord started with pid 7
2017-03-29 12:20:16,279 INFO spawned: 'mongod' with pid 11
2017-03-29 12:20:16,281 INFO spawned: 'apache2' with pid 12
2017-03-29 12:20:17,676 INFO success: mongod entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-03-29 12:20:17,676 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
about to fork child process, waiting until server is ready for connections.
forked process: 75
child process started successfully, parent exiting
2017-03-29 12:20:33,399 INFO exited: mongod (exit status 48; not expected)
Traceback (most recent call last):
  File "/data/crits/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/crits/crits/settings.py", line 117, in <module>
    execfile(dbfile)
ValueError: invalid \x escape

$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false`

I've followed the install instructions and created the ~/crits-data folder and set the correct permissions on it, however no dice.

Is there anything obviously wrong that I am doing that would cause this issue?

**Comment by battletux** [comment]
Strange, I built the Crits container locally using the Dockerfile here and apart from mongoDB complaining about too many failed startups it appears to be working.

`Drop protection does not apply to effective TLDs
2017-03-29 15:38:26,440 INFO spawned: 'mongod' with pid 113
2017-03-29 15:38:26,474 INFO exited: mongod (exit status 100; not expected)
2017-03-29 15:38:28,484 INFO spawned: 'mongod' with pid 117
2017-03-29 15:38:28,508 INFO exited: mongod (exit status 100; not expected)
2017-03-29 15:38:31,521 INFO spawned: 'mongod' with pid 121
2017-03-29 15:38:31,546 INFO exited: mongod (exit status 100; not expected)
2017-03-29 15:38:32,548 INFO gave up: mongod entered FATAL state, too many start retries too quickly`

**Comment by nremynse** [comment]
Also seeing the same issue: 

Traceback (most recent call last):
  File "/data/crits/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/crits/crits/settings.py", line 117, in <module>
    execfile(dbfile)
ValueError: invalid \x escape


Running most recent .ova file for REMnux and the below docker version:

**Comment by jsedberr** [comment]
I had this same issue:

$ docker run -it -p 8443:8443 remnux/crits
2017-12-13 14:31:23,945 CRIT Set uid to user 999
2017-12-13 14:31:23,980 INFO RPC interface 'supervisor' initialized
2017-12-13 14:31:23,980 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-12-13 14:31:23,980 INFO supervisord started with pid 5
2017-12-13 14:31:24,982 INFO spawned: 'mongod' with pid 9
2017-12-13 14:31:24,984 INFO spawned: 'apache2' with pid 10
2017-12-13 14:31:26,297 INFO success: mongod entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-12-13 14:31:26,297 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
about to fork child process, waiting until server is ready for connections.
forked process: 80
child process started successfully, parent exiting
Traceback (most recent call last):
  File "/data/crits/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/crits/crits/settings.py", line 117, in <module>
    execfile(dbfile)
ValueError: invalid \x escape

-------------------------------------------------------------------------------------------------------

Line 117 of settings.py is attempting to load /data/crits/crits/config/database.py. In this file there is a SECRET_KEY with a default value that contains a string literal with a \x character.

# This is an example file. You should copy this to "database.py" and
# make your changes there.
# Modifying this example file will not change the settings that CRITs uses.


# MongoDB connection information
MONGO_HOST = 'localhost'      # server to connect to
MONGO_PORT = 27017            # port MongoD is running on
MONGO_DATABASE = 'crits'      # database name to connect to
# The following optional settings should only be changed if you specifically
# enabled and configured them during your MongoDB installation
# See http://docs.mongodb.org/v2.4/administration/security/ regarding implementation
MONGO_SSL = False             # whether MongoD has SSL enabled
MONGO_USER = ''               # mongo user with "readWrite" role in the database
MONGO_PASSWORD = ''           # password for the mongo user
MONGO_REPLICASET = None       # name of RS, if mongod in Replicaset

# Set this to a sufficiently long random string. We recommend running
# the following code from a python shell to generate the string and pasting
# the output here.
#
#from django.utils.crypto import get_random_string as grs
#SECRET_KEY = grs(50, 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)')
SECRET_KEY = 'z_dCJ&](Ku4fv2e+1gx3m;mL\-\x*S!:-\J*TbD+a!TfMBaTL'

# DB to use for files
FILE_DB = GRIDFS # Set to S3 (NO QUOTES) to use S3. You'll also want to set
                 # the stuff below and create your buckets.

# Separator to use in bucket names (if needed)
#S3_SEPARATOR = '.'

# Unique ID to append to bucket names (if needed)
#S3_ID=""

# S3 credentials (if needed)
#AWS_ACCESS_KEY_ID = ""
#AWS_SECRET_ACCESS_KEY = ""

# If your S3 location is somewhere other than s3.amazonaws.com, then you
# can specify a different hostname here. (if needed)
#S3_HOSTNAME = ""
--------------------------------------------------------------------------------------------------------

I created a container by running:
docker run -it -p 8443:8443 --entrypoint bash remnux/crits

replaced the file database.py by using:
docker cp LOCAL_DATABASE.PY CONTAINER:/data/crits/crits/config/database.py

Then you can run the commands saved in the original entry point value and the server starts as expected.

comments in database.py recommend to run the python commands below out-of-band and replace the default SECRET_KEY value with the results:

from django.utils.crypto import get_random_string as grs
SECRET_KEY = grs(50, 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)')

I just uncommented these lines in database.py and commented out the default secret key. 

Hope this helps!
