### ISSUE TITLE
remnux/jsdetox console not defined.

### ISSUE THREAD

**Issue by Jared-Harrington-Gibbs** [REMnux/docker#20]
I just downloaded the image and have been having issues executing seemingly simple code samples.

**Sample submitted**
```
console['\x6c\x6f\x67']('\x4e\x65\x74\x53\x65\x63\x20\x66\x6f\x72\x20\x74\x68\x65\x20\x77\x69\x6e\x21');
```
**Decoded Form**
`
console['log']('NetSec for the win!');
`
&nbsp;

**Error when selecting "Execute"**
> console is not defined (Line 1)

**docker command**
`docker run --rm -d --name=js -p 3000:3000 remnux/jsdetox`

**error trace**
``` at <eval>:1:1,/home/nonroot/jsdetox/lib/framework/jsengine_v8.rb:215:in `execute',/home/nonroot/jsdetox/app/controllers/backend.rb:32:in `block (2 levels) in <top (required)>',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/application/routing.rb:569:in `call',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/application/routing.rb:569:in `block in route',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/application/routing.rb:51:in `[]',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/application/routing.rb:51:in `block (3 levels) in process_destination_path',/var/lib/gems/1.9.1/gems/sinatra-1.3.6/lib/sinatra/base.rb:876:in `route_eval',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/application/routing.rb:51:in `block (2 levels) in process_destination_path',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/application/routing.rb:51:in `catch',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/application/routing.rb:51:in `block in process_destination_path',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/application/routing.rb:25:in `instance_eval',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/application/routing.rb:25:in `process_destination_path',(eval):134:in `block (2 levels) in inject_root_methods',(eval):124:in `catch',(eval):124:in `block in inject_root_methods',/var/lib/gems/1.9.1/gems/http_router-0.10.2/lib/http_router/node/root.rb:92:in `[]',/var/lib/gems/1.9.1/gems/http_router-0.10.2/lib/http_router.rb:119:in `block in call',/var/lib/gems/1.9.1/gems/http_router-0.10.2/lib/http_router.rb:119:in `catch',/var/lib/gems/1.9.1/gems/http_router-0.10.2/lib/http_router.rb:119:in `call',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/application/routing.rb:919:in `route!',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/application/routing.rb:909:in `dispatch!',/var/lib/gems/1.9.1/gems/sinatra-1.3.6/lib/sinatra/base.rb:794:in `block in call!',/var/lib/gems/1.9.1/gems/sinatra-1.3.6/lib/sinatra/base.rb:946:in `block in invoke',/var/lib/gems/1.9.1/gems/sinatra-1.3.6/lib/sinatra/base.rb:946:in `catch',/var/lib/gems/1.9.1/gems/sinatra-1.3.6/lib/sinatra/base.rb:946:in `invoke',/var/lib/gems/1.9.1/gems/sinatra-1.3.6/lib/sinatra/base.rb:794:in `call!',/var/lib/gems/1.9.1/gems/sinatra-1.3.6/lib/sinatra/base.rb:780:in `call',/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context',/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call',/var/lib/gems/1.9.1/gems/sass-3.4.13/lib/sass/plugin/rack.rb:54:in `call',/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/head.rb:13:in `call',/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/reloader.rb:250:in `call',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/logger.rb:388:in `call',/var/lib/gems/1.9.1/gems/sinatra-1.3.6/lib/sinatra/showexceptions.rb:21:in `call',/var/lib/gems/1.9.1/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in `block in call',/var/lib/gems/1.9.1/gems/sinatra-1.3.6/lib/sinatra/base.rb:1499:in `synchronize',/var/lib/gems/1.9.1/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in `call',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/router.rb:83:in `block in call',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/router.rb:76:in `each',/var/lib/gems/1.9.1/gems/padrino-core-0.10.6/lib/padrino-core/router.rb:76:in `call',/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service',/usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service',/usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run',/usr/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread' ```

**Comment by Jared-Harrington-Gibbs** [comment]
closing due to inactivity
