### ISSUE TITLE
Image: Viper - Build Code: bebvmjmpehchmegxdvpfnef - Fail on start

### ISSUE THREAD

**Issue by elauqsap** [REMnux/docker#6]
```
$ docker pull remnux/viper
```
```
Using default tag: latest
latest: Pulling from remnux/viper
428b411c28f0: Already exists
435050075b3f: Already exists
9fd3c8c9af32: Already exists
6d4946999d4f: Already exists
48a17bbb873c: Already exists
867807986fef: Already exists
27be8f6c8544: Already exists
2ba986d42ba3: Already exists
c97df9abfe2f: Already exists
ae7bd011e13b: Already exists
cf140d12eb70: Already exists
9cf0507a9518: Already exists
6dd8a12e04f3: Already exists
bd820b776c8a: Already exists
0a8c71adbf02: Already exists
5d4cc60cacd7: Already exists
a897f7d62db8: Already exists
6da6edfb4041: Already exists
023fa33a1f05: Already exists
490271e609b9: Already exists
c5cf2081ee4f: Already exists
Digest: sha256:5939b811f0e2e123768fa7bd2dacd3ea6d4aa0b5ed7718dfd0d7667c3f118a55
Status: Image is up to date for remnux/viper:latest
```
```
$ docker run --rm -it -v ~/viper:/home/nonroot/workdir remnux/viper
```
```
Traceback (most recent call last):
  File "../viper/viper.py", line 17, in <module>
    c = console.Console()
  File "/home/nonroot/viper/viper/core/ui/console.py", line 45, in __init__
    self.cmd = Commands()
  File "/home/nonroot/viper/viper/core/ui/commands.py", line 27, in __init__
    self.db = Database()
  File "/home/nonroot/viper/viper/core/database.py", line 147, in __init__
    Base.metadata.create_all(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 3622, in create_all
    tables=tables)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1853, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1846, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2037, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2076, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2072, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 708, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1146, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 602, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
```

**Comment by lennyzeltser** [comment]
I suspect you're encountering this issue because the ~/viper directory on your host is not world-writable. Before invoking the remnux/viper container, make sure that ~/viper exists and also set its permissions to be world-writable (`chmod a+xwr ~/viper`).

**Comment by elauqsap** [comment]
I followed the instructions and made sure it was world-writable. I think the issue is that it is writing the file `viper.db` as `rw` but it can't execute. When I modified the files after starting it twice I was able to get it to work.
```
$ ls -la viper
total 24
drwxrwxrwx  3 dev  staff    102 Sep  2 16:21 .
drwxrwxrwx  5 dev  staff    170 Aug 28 00:57 ..
-rw-------  1 dev  staff  11264 Aug 28 00:59 viper.db
```
```
$ chmod 777 viper/viper.db
```
```
$ docker run --rm -it -v ~/remnux/viper:/home/nonroot/workdir remnux/viper
         _
        (_)
   _   _ _ ____  _____  ____
  | | | | |  _ \| ___ |/ ___)
   \ V /| | |_| | ____| |
    \_/ |_|  __/|_____)_| v1.3-dev
          |_|

You have 0 files in your default repository
viper > exit
```
```
$ docker run --rm -it -v ~/remnux/viper:/home/nonroot/workdir remnux/viper
         _
        (_)
   _   _ _ ____  _____  ____
  | | | | |  _ \| ___ |/ ___)
   \ V /| | |_| | ____| |
    \_/ |_|  __/|_____)_| v1.3-dev
          |_|

You have 0 files in your default repository
Traceback (most recent call last):
  File "../viper/viper.py", line 18, in <module>
    c.start()
  File "/home/nonroot/viper/viper/core/ui/console.py", line 166, in start
    readline.read_history_file(history_path)
IOError: [Errno 13] Permission denied
```
```
$ chmod 777 viper/viperhistory
```
Works every time after this point, I am still looking for a solution to this issue. I am guessing you haven't experience this?
```
$ docker run --rm -it -v ~/remnux/viper:/home/nonroot/workdir remnux/viper
         _
        (_)
   _   _ _ ____  _____  ____
  | | | | |  _ \| ___ |/ ___)
   \ V /| | |_| | ____| |
    \_/ |_|  __/|_____)_| v1.3-dev
          |_|

You have 0 files in your default repository
viper > exit
```
```
docker run --rm -it -v ~/remnux/viper:/home/nonroot/workdir remnux/viper
         _
        (_)
   _   _ _ ____  _____  ____
  | | | | |  _ \| ___ |/ ___)
   \ V /| | |_| | ____| |
    \_/ |_|  __/|_____)_| v1.3-dev
          |_|

You have 0 files in your default repository
viper > exit
```
